routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome'); 
});
Auth::routes();
Route::get('login','loginController@login');
Route::post('login','loginController@masuk');
Route::post('logout','loginController@keluar');
Route::post('daftar','loginController@mendaftar');
Route::get('daftar','loginController@daftar');

Route::group(['middleware' => ['web', 'auth', 'permission'] ], function () {

	Route::get('dashboard', 'berkasController@break')->name('home.dashboard');

	//user
	Route::resource('pemilik-akun','userController');
	//role dan pembagian lomba
	Route::resource('role-akun','RoleController');
	Route::get('permission-akun/{id}','RoleController@permissions')->name('role-akun.permissions');
	Route::post('permission-akun/{id}','RoleController@simpan')->name('role-akun.simpan');

	//provinsi
	Route::resource('provinsi','ProvinsiController');
	//kabupaten - kota
	Route::resource('kabupaten-kota','KabKotaController');
	//kecamatan
	Route::resource('kecamatan','kecamatanController');
	//sekolah
	Route::resource('sekolah','SekolahController');
	//universitas
	Route::resource('universitas','UniversitasController');
	//pelajar-profil
	Route::resource('pelajar-profil','PelajarProfilController');
	//mahasiswa-profil
	Route::resource('mahasiswa','MahasiswaProfilController');
	//kelompok
	Route::resource('kelompok', 'KelompokController');
	//kegiatan
	route::resource('kegiatan', 'KegiatanController');
	//user lomba
	route::resource('user-lomba', 'UserLombaController');

	//berkas-user
	route::get('berkas/{user}/{id}', 'berkasController@index')->name('berkas.index');
	//hackathon-user
	route::get('hackathon/{user}/{id}', 'berkasController@indexhack')->name('hackathon.index');
	//ktm
	route::patch('upload-ktm/{id}', 'berkasController@ktm')->name('hackathon.ktm');
	//foto
	route::patch('upload-foto/{id}', 'berkasController@foto');
	//bayar hackathon
	route::patch('upload-bayar/{id}', 'berkasController@bayar');
	//membuat group
	route::post('hackathon-gruop', 'berkasController@makegrup')->name('hackathon.grup');
	//menambahkan anggota
	route::post('hackathon-anggota', 'berkasController@addanggota')->name('hackathon.addanggota');
	//proposal
	route::post('upload-proposal/{id}', 'berkasController@addproposal')->name('hackathon.proposal');
	route::DELETE('del-proposal/{id}/delete', 'berkasController@dellproposal')->name('hackathon.dellproposal');

	route::get('password', 'userController@password');
	route::patch('gantipassword', 'userController@ganti');

	route::get('profil/{nama}/{id}','userController@profil');
	route::get('editprofil/{nama}/{id}','userController@editprofil');

	route::get('bukti-pembayaran','userController@bukti');
	route::post('perbaruiprofil', 'userController@simpanprofil');
});

	//membuka img
	route::get('foto/{type}/{file_id}', 'berkasController@file');
	route::get('tambah-sekolah', 'SekolahController@sekolah');
	route::get('tambah-universitas', 'UniversitasController@universitas');
	route::post('tambah-universitas', 'UniversitasController@simpanuni');
	route::post('tambah-sekolah', 'SekolahController@simpanseko');
	
	route::get('olimpiade-Komputer','KegiatanController@olkom');
	route::get('hackathon','KegiatanController@hack');
	route::get('faq','KegiatanController@faq');
	route::post('faqt','KegiatanController@faqt');

app/provinsi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class provinsi extends Model
{
    protected $table = 'provinsis';

	const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

     protected $casts = [
        'nama_prov' => 'string',
    ];

    protected $fillable = [
        'nama_prov',
    ];
}

app/Http/Controllers/ProvinsiController.php
<?php

namespace App\Http\Controllers;

use App\provinsi;
use Illuminate\Http\Request;

class ProvinsiController extends Controller
{
    
    public function index()
    {
        $provinsis = provinsi::all();
        return view('provinsi.index',compact('provinsis'));
    }
 
    
    public function create()
    {
        return view('provinsi.create');
    }

    
    public function store(Request $request)
    {
        $request->validate([
            'nama_prov' => 'required|unique:provinsis'
        ]);

        $provinsi = new provinsi;
        $provinsi->nama_prov = $request->nama_prov;
        if($provinsi->save()){
            return redirect()->route('provinsi.index');
        }else{
            return redirect()->back();
        }
    }

    
    public function show(provinsi $provinsi)
    {
        return redirect()->back();
    }

    
    public function edit(provinsi $provinsi)
    {
        return view('provinsi.edit',compact('provinsi'));
    }

    
    public function update(Request $request, provinsi $provinsi)
    {
        $request->validate([
            'nama_prov' => 'required'
        ]);
        $provinsi->nama_prov = $request->nama_prov;
        if($provinsi->save()){
            return redirect()->route('provinsi.index');
        }else{
            return redirect()->back();
        }
    }

    
    public function destroy(provinsi $provinsi)
    {
        if($provinsi->delete()){
            return redirect()->route('provinsi.index');
        }else{
            return redirect()->back();
        }
    }
}

resources/views/provinsi/_form.blade.php
<div class="form-group form-float">
    <div class="form-line">
        {!! Form::text('nama_prov', null, ['class'=>'form-control','maxlength'=>'30', 'minlength'=>'3']) !!}
        <label class="form-label">Nama Provinsi</label>
    </div>
    <div class="help-info">Min. 3, Max. 30 characters</div>
</div>

resources/views/provinsi/create.blade.php
@extends('potongan.main')

@section('title')
	Create Provinsi
@stop

@section('content')
	<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>Create Provinsi</h2>
                </div>
                <div class="body">
                    {{ Form::open(array('url' => route('provinsi.store'), 'files' => true)) }}
                        
                        @include('provinsi._form')

                        <br>
                        <div class="text-center">
                            <button type="reset" class="btn btn-primary m-t-15 waves-effect">Reset</button>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Simpan</button>
                            <a href="{{ route('provinsi.index') }}" class="btn btn-primary m-t-15 waves-effect">Back</a>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')
	
    <!-- Jquery Validation Plugin Css -->
    <script src="{{ asset('template/plugins/jquery-validation/jquery.validate.js') }}"></script>

    <!-- JQuery Steps Plugin Js -->
    <script src="{{ asset('template/plugins/jquery-steps/jquery.steps.js') }}"></script>

    <!-- Sweet Alert Plugin Js -->
    <script src="{{ asset('template/plugins/sweetalert/sweetalert.min.js') }}"></script>

	<script src="{{ asset('template/js/pages/forms/form-validation.js') }}"></script>
	
@stop

@section('style')
	<link href="{{ asset('template/plugins/sweetalert/sweetalert.css') }}" rel="stylesheet" />
@stop

resources/views/provinsi/edit.blade.php
@extends('potongan.main')

@section('title')
	Edit Provinsi {{$provinsi->nama_prov}}
@stop

@section('content')
	<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Edit Provinsi {{$provinsi->nama_prov}}
                        <small></small>
                    </h2>
                </div>
                <div class="body">
                    {{ Form::model($provinsi, array('method' => 'PATCH', 'url' => route('provinsi.update', $provinsi->id), 'files' => true)) }}
                    
                    	@include('provinsi._form')

                        <br>
                        <div class="text-center">
                            <button type="reset" class="btn btn-primary m-t-15 waves-effect">Reset</button>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Simpan</button>
                            <a href="{{ route('provinsi.index') }}" class="btn btn-primary m-t-15 waves-effect">Back</a>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')
    <!-- Jquery Validation Plugin Css -->
    <script src="{{ asset('template/plugins/jquery-validation/jquery.validate.js') }}"></script>

    <!-- JQuery Steps Plugin Js -->
    <script src="{{ asset('template/plugins/jquery-steps/jquery.steps.js') }}"></script>

    <!-- Sweet Alert Plugin Js -->
    <script src="{{ asset('template/plugins/sweetalert/sweetalert.min.js') }}"></script>

	<script src="{{ asset('template/js/pages/forms/form-validation.js') }}"></script>
	
@stop

@section('style')
	<link href="{{ asset('template/plugins/sweetalert/sweetalert.css') }}" rel="stylesheet" />
@stop

resources/views/provinsi/index.blade.php
@extends('potongan.main')

@section('title')
	Provinsi
@stop

@section('style')

	<link href="{{ asset('template/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet" />

@stop
@section('content')
    <!-- Exportable Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Provinsi Table
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <a href="{{ route('provinsi.create') }}" class="btn bg-blue-grey waves-effect" class=" text-center">Add Provinsi
                    	</a>
                    </ul>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover dataTable js-exportable no-footer" id="tbluser">
                            <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th class="text-center">Nama</th>
                                    <th class="text-center">Jumlah Kabupaten dan Kota</th>
                                    <th class="text-center">Action</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th class="text-center">Nama</th>
                                    <th class="text-center">Jumlah Kabupaten dan Kota</th>
                                    <th class="text-center">Action</th>
                                </tr>
                            </tfoot>
                            <tbody>
                            	<?php $no=0?>
                            	@foreach($provinsis as $provinsi)
	                                <tr>
	                                    <td class="text-center">{{++$no}}</td>
	                                    <td>{{$provinsi->nama_prov}}</td>
	                                    <td class="text-center">999+</td>
	                                    <td>
                                            <a href="{{ route('provinsi.edit',$provinsi->id) }}" class="btn btn-info btn-xs waves-effect">Edit</a>
                                            {!! Form::open(['method'=>'DELETE', 'route' => ['provinsi.destroy', $provinsi->id], 'style' => 'display:inline']) !!}
                                            {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs waves-effect','id'=>'delete-confirm']) !!}
                                            {!! Form::close() !!}
                                        </td>
	                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Exportable Table -->
@stop

@section('script')
	
    <script src="{{ asset('template/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script type="text/javascript">
        $('.js-exportable').DataTable({
            'info' : false,
            dom: 'Bfrtip',
            responsive: true,
            buttons: [
                'copy', 'csv', 'excel', 'pdf',
            ]
        });

        $("input#delete-confirm").on("click", function(){
            return confirm("Apakah Kamu Ingin Menghapus Provinsi Ini?");
        });
    </script>
    
@stop