routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome'); 
});
Auth::routes();
Route::get('login','loginController@login');
Route::post('login','loginController@masuk');
Route::post('logout','loginController@keluar');
Route::post('daftar','loginController@mendaftar');
Route::get('daftar','loginController@daftar');

Route::group(['middleware' => ['web', 'auth', 'permission'] ], function () {

	Route::get('dashboard', 'berkasController@break')->name('home.dashboard');

	//user
	Route::resource('pemilik-akun','userController');
	//role dan pembagian lomba
	Route::resource('role-akun','RoleController');
	Route::get('permission-akun/{id}','RoleController@permissions')->name('role-akun.permissions');
	Route::post('permission-akun/{id}','RoleController@simpan')->name('role-akun.simpan');

	//provinsi
	Route::resource('provinsi','ProvinsiController');
	//kabupaten - kota
	Route::resource('kabupaten-kota','KabKotaController');
	//kecamatan
	Route::resource('kecamatan','kecamatanController');
	//sekolah
	Route::resource('sekolah','SekolahController');
	//universitas
	Route::resource('universitas','UniversitasController');
	//pelajar-profil
	Route::resource('pelajar-profil','PelajarProfilController');
	//mahasiswa-profil
	Route::resource('mahasiswa','MahasiswaProfilController');
	//kelompok
	Route::resource('kelompok', 'KelompokController');
	//kegiatan
	route::resource('kegiatan', 'KegiatanController');
	//user lomba
	route::resource('user-lomba', 'UserLombaController');

	//berkas-user
	route::get('berkas/{user}/{id}', 'berkasController@index')->name('berkas.index');
	//hackathon-user
	route::get('hackathon/{user}/{id}', 'berkasController@indexhack')->name('hackathon.index');
	//ktm
	route::patch('upload-ktm/{id}', 'berkasController@ktm')->name('hackathon.ktm');
	//foto
	route::patch('upload-foto/{id}', 'berkasController@foto');
	//bayar hackathon
	route::patch('upload-bayar/{id}', 'berkasController@bayar');
	//membuat group
	route::post('hackathon-gruop', 'berkasController@makegrup')->name('hackathon.grup');
	//menambahkan anggota
	route::post('hackathon-anggota', 'berkasController@addanggota')->name('hackathon.addanggota');
	//proposal
	route::post('upload-proposal/{id}', 'berkasController@addproposal')->name('hackathon.proposal');
	route::DELETE('del-proposal/{id}/delete', 'berkasController@dellproposal')->name('hackathon.dellproposal');

	route::get('password', 'userController@password');
	route::patch('gantipassword', 'userController@ganti');

	route::get('profil/{nama}/{id}','userController@profil');
	route::get('editprofil/{nama}/{id}','userController@editprofil');

	route::get('bukti-pembayaran','userController@bukti');
	route::post('perbaruiprofil', 'userController@simpanprofil');
});

	//membuka img
	route::get('foto/{type}/{file_id}', 'berkasController@file');
	route::get('tambah-sekolah', 'SekolahController@sekolah');
	route::get('tambah-universitas', 'UniversitasController@universitas');
	route::post('tambah-universitas', 'UniversitasController@simpanuni');
	route::post('tambah-sekolah', 'SekolahController@simpanseko');
	
	route::get('olimpiade-Komputer','KegiatanController@olkom');
	route::get('hackathon','KegiatanController@hack');
	route::get('faq','KegiatanController@faq');
	route::post('faqt','KegiatanController@faqt');

app/kab_kota.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class kab_kota extends Model
{
    protected $table = 'kab_kotas';

	const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

     protected $casts = [
        'nama_kab_kota' => 'string',
        'prov_id' => 'integer',
    ];

    protected $fillable = [
        'nama_kab_kota',
        'prov_id',
    ];


    public function provinsi()
    {
        return $this->belongsTo(provinsi::class, 'prov_id', 'id');
    }
}

app/Http/Controllers/KabKotaController.php
<?php

namespace App\Http\Controllers;

use App\kab_kota;
use App\provinsi;
use Illuminate\Http\Request;

class KabKotaController extends Controller
{ 
    
    public function index()
    {
        $kab_kotas = kab_kota::all();
        //dd($kab_kotas);
        return view('kab_kota.index',compact('kab_kotas'));
    }

    
    public function create()
    {
        $prov = provinsi::pluck('nama_prov','id');
        return view('kab_kota.create',compact('prov'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama_kab_kota' => 'required|unique:kab_kotas',
            'prov_id' => 'required',
        ]);
        $kab_kota = new kab_kota;
        $kab_kota->nama_kab_kota = $request->nama_kab_kota;
        $kab_kota->prov_id = $request->prov_id;
        if($kab_kota->save()){
            return redirect()->route('kabupaten-kota.index');
        }else{
            return redirect()->back();
        }
    }

    
    public function show(kab_kota $kab_kota)
    {
        return redirect()->back();
    }

    public function edit($kab_kota)
    {
        $kab_kota = kab_kota::find($kab_kota);
        
        $prov = provinsi::pluck('nama_prov','id');
        return view('kab_kota.edit',compact('prov','kab_kota'));
    }

    public function update(Request $request, $kab_kota)
    {
        $request->validate([
            'nama_kab_kota' => 'required',
            'prov_id' => 'required',
        ]);
        $kab_kota = kab_kota::find($kab_kota);
        $kab_kota->nama_kab_kota = $request->nama_kab_kota;
        $kab_kota->prov_id = $request->prov_id;
        if($kab_kota->save()){
            return redirect()->route('kabupaten-kota.index');
        }else{
            return redirect()->back();
        }
    }


    public function destroy($kab_kota)
    {
        $kab_kota = kab_kota::find($kab_kota);
        if($kab_kota->delete()){
            return redirect()->route('kabupaten-kota.index');
        }else{
            return redirect()->back();
        }
    }
}

resources/views/kab_kota/_form.blade.php
<div class="form-group form-float">
    <div class="form-line">
        {!! Form::text('nama_kab_kota', null, ['class'=>'form-control','maxlength'=>'30', 'minlength'=>'3', 'required']) !!}
        <label class="form-label">Nama Kabupaten & Kota</label>
    </div>
    <div class="help-info">Min. 3, Max. 30 characters</div>
</div>

<div class="form-group">
	<p>
	    <b>Provinsi</b>
	</p>
	{!! Form::select('prov_id', $prov,null, ['class'=>'form-control show-tick', 'required', 'data-live-search'=>'true']) !!}
</div>

resources/views/kab_kota/create.blade.php
@extends('potongan.main')

@section('title')
	Create Kabupaten & Kota
@stop

@section('content')
	<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>Create Kabupaten & Kota</h2>
                </div>
                <div class="body">
                    {{ Form::open(array('url' => route('kabupaten-kota.store'), 'files' => true)) }}
                        
                        @include('kab_kota._form')

                        <br>
                        <div class="text-center">
                            <button type="reset" class="btn btn-primary m-t-15 waves-effect">Reset</button>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Simpan</button>
                            <a href="{{ route('kabupaten-kota.index') }}" class="btn btn-primary m-t-15 waves-effect">Back</a>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')
    <!-- Jquery Validation Plugin Css -->
    <script src="{{ asset('template/plugins/jquery-validation/jquery.validate.js') }}"></script>

    <!-- JQuery Steps Plugin Js -->
    <script src="{{ asset('template/plugins/jquery-steps/jquery.steps.js') }}"></script>

    <!-- Sweet Alert Plugin Js -->
    <script src="{{ asset('template/plugins/sweetalert/sweetalert.min.js') }}"></script>

    <script src="{{ asset('template/js/pages/forms/form-validation.js') }}"></script>

    <!-- Multi Select Plugin Js -->
    <script src="{{ asset('template/plugins/multi-select/js/jquery.multi-select.js') }}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset('template/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>
{{-- 
    <script src="{{ asset('template/js/pages/forms/advanced-form-elements.js') }}"></script>
     --}}
@stop

@section('style')

    <!-- Multi Select Css -->
    <link href="{{ asset('template/plugins/multi-select/css/multi-select.css') }}" rel="stylesheet">

    <!-- Bootstrap Select Css -->
    <link href="{{ asset('template/plugins/bootstrap-select/css/bootstrap-select.css') }}" rel="stylesheet" />

    <link href="{{ asset('template/plugins/sweetalert/sweetalert.css') }}" rel="stylesheet" />
@stop

resources/views/kab_kota/edit.blade.php
@extends('potongan.main')

@section('title')
	Edit {{$kab_kota->nama_kab_kota}}
@stop

@section('content')
	<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Edit {{$kab_kota->id}}
                        <small></small>
                    </h2>
                </div>
                <div class="body">
                    {{ Form::model($kab_kota, array('method' => 'PATCH', 'url' => route('kabupaten-kota.update', $kab_kota->id), 'files' => true)) }}
                    
                    	@include('kab_kota._form')

                        <br>
                        <div class="text-center">
                            <button type="reset" class="btn btn-primary m-t-15 waves-effect">Reset</button>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Simpan</button>
                            <a href="{{ route('kabupaten-kota.index') }}" class="btn btn-primary m-t-15 waves-effect">Back</a>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')
    <!-- Jquery Validation Plugin Css -->
    <script src="{{ asset('template/plugins/jquery-validation/jquery.validate.js') }}"></script>

    <!-- JQuery Steps Plugin Js -->
    <script src="{{ asset('template/plugins/jquery-steps/jquery.steps.js') }}"></script>

    <!-- Sweet Alert Plugin Js -->
    <script src="{{ asset('template/plugins/sweetalert/sweetalert.min.js') }}"></script>

    <script src="{{ asset('template/js/pages/forms/form-validation.js') }}"></script>

    <!-- Multi Select Plugin Js -->
    <script src="{{ asset('template/plugins/multi-select/js/jquery.multi-select.js') }}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset('template/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>
{{-- 
    <script src="{{ asset('template/js/pages/forms/advanced-form-elements.js') }}"></script>
     --}}
@stop

@section('style')

    <!-- Multi Select Css -->
    <link href="{{ asset('template/plugins/multi-select/css/multi-select.css') }}" rel="stylesheet">

    <!-- Bootstrap Select Css -->
    <link href="{{ asset('template/plugins/bootstrap-select/css/bootstrap-select.css') }}" rel="stylesheet" />

    <link href="{{ asset('template/plugins/sweetalert/sweetalert.css') }}" rel="stylesheet" />
@stop

resources/views/kab_kota/index.blade.php
@extends('potongan.main')

@section('title')
	Kabupaten & Kota
@stop

@section('style')

	<link href="{{ asset('template/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet" />

@stop
@section('content')
    <!-- Exportable Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Kabupaten & Kota Table
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <a href="{{ route('kabupaten-kota.create') }}" class="btn bg-blue-grey waves-effect" class=" text-center">Add Kabupaten & Kota
                    	</a>
                    </ul>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover dataTable js-exportable no-footer" id="tbluser">
                            <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th class="text-center">Nama</th>
                                    <th class="text-center">Jumlah Kecamatan</th>
                                    <th class="text-center">Provinsi</th>
                                    <th class="text-center">Action</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th class="text-center">Nama</th>
                                    <th class="text-center">Jumlah Kecamatan</th>
                                    <th class="text-center">Provinsi</th>
                                    <th class="text-center">Action</th>
                                </tr>
                            </tfoot>
                            <tbody>
                            	<?php $no=0?>
                            	@foreach($kab_kotas as $kab_kota)
	                                <tr>
	                                    <td class="text-center">{{++$no}}</td>
	                                    <td>{{$kab_kota->nama_kab_kota}}</td>
                                        <td class="text-center">999+</td>
                                        <td>{{$kab_kota->provinsi->nama_prov}}</td>
	                                    <td>
                                            <a href="{{ route('kabupaten-kota.edit',$kab_kota->id) }}" class="btn btn-info btn-xs waves-effect">Edit</a>
                                            {!! Form::open(['method'=>'DELETE', 'route' => ['kabupaten-kota.destroy', $kab_kota->id], 'style' => 'display:inline']) !!}
                                            {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs waves-effect','id'=>'delete-confirm']) !!}
                                            {!! Form::close() !!}
                                        </td>
	                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Exportable Table -->
@stop

@section('script')
	
    <script src="{{ asset('template/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script type="text/javascript">
        $('.js-exportable').DataTable({
            'info' : false,
            dom: 'Bfrtip',
            responsive: true,
            buttons: [
                'copy', 'csv', 'excel', 'pdf',
            ]
        });

        $("input#delete-confirm").on("click", function(){
            return confirm("Apakah Kamu Ingin Menghapus Kabupaten & kota Ini?");
        });
    </script>
    
@stop