routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome'); 
});
Auth::routes();
Route::get('login','loginController@login');
Route::post('login','loginController@masuk');
Route::post('logout','loginController@keluar');
Route::post('daftar','loginController@mendaftar');
Route::get('daftar','loginController@daftar');

Route::group(['middleware' => ['web', 'auth', 'permission'] ], function () {

	Route::get('dashboard', 'berkasController@break')->name('home.dashboard');

	//user
	Route::resource('pemilik-akun','userController');
	//role dan pembagian lomba
	Route::resource('role-akun','RoleController');
	Route::get('permission-akun/{id}','RoleController@permissions')->name('role-akun.permissions');
	Route::post('permission-akun/{id}','RoleController@simpan')->name('role-akun.simpan');

	//provinsi
	Route::resource('provinsi','ProvinsiController');
	//kabupaten - kota
	Route::resource('kabupaten-kota','KabKotaController');
	//kecamatan
	Route::resource('kecamatan','kecamatanController');
	//sekolah
	Route::resource('sekolah','SekolahController');
	//universitas
	Route::resource('universitas','UniversitasController');
	//pelajar-profil
	Route::resource('pelajar-profil','PelajarProfilController');
	//mahasiswa-profil
	Route::resource('mahasiswa','MahasiswaProfilController');
	//kelompok
	Route::resource('kelompok', 'KelompokController');
	//kegiatan
	route::resource('kegiatan', 'KegiatanController');
	//user lomba
	route::resource('user-lomba', 'UserLombaController');

	//berkas-user
	route::get('berkas/{user}/{id}', 'berkasController@index')->name('berkas.index');
	//hackathon-user
	route::get('hackathon/{user}/{id}', 'berkasController@indexhack')->name('hackathon.index');
	//ktm
	route::patch('upload-ktm/{id}', 'berkasController@ktm')->name('hackathon.ktm');
	//foto
	route::patch('upload-foto/{id}', 'berkasController@foto');
	//bayar hackathon
	route::patch('upload-bayar/{id}', 'berkasController@bayar');
	//membuat group
	route::post('hackathon-gruop', 'berkasController@makegrup')->name('hackathon.grup');
	//menambahkan anggota
	route::post('hackathon-anggota', 'berkasController@addanggota')->name('hackathon.addanggota');
	//proposal
	route::post('upload-proposal/{id}', 'berkasController@addproposal')->name('hackathon.proposal');
	route::DELETE('del-proposal/{id}/delete', 'berkasController@dellproposal')->name('hackathon.dellproposal');

	route::get('password', 'userController@password');
	route::patch('gantipassword', 'userController@ganti');

	route::get('profil/{nama}/{id}','userController@profil');
	route::get('editprofil/{nama}/{id}','userController@editprofil');

	route::get('bukti-pembayaran','userController@bukti');
	route::post('perbaruiprofil', 'userController@simpanprofil');
});

	//membuka img
	route::get('foto/{type}/{file_id}', 'berkasController@file');
	route::get('tambah-sekolah', 'SekolahController@sekolah');
	route::get('tambah-universitas', 'UniversitasController@universitas');
	route::post('tambah-universitas', 'UniversitasController@simpanuni');
	route::post('tambah-sekolah', 'SekolahController@simpanseko');
	
	route::get('olimpiade-Komputer','KegiatanController@olkom');
	route::get('hackathon','KegiatanController@hack');
	route::get('faq','KegiatanController@faq');
	route::post('faqt','KegiatanController@faqt');

app/role.php
<?php

namespace App;

use Cartalyst\Sentinel\Permissions\PermissibleInterface;
use Cartalyst\Sentinel\Permissions\PermissibleTrait;
use Illuminate\Database\Eloquent\Model;
use Cartalyst\Sentinel\Roles\RoleInterface;
use Illuminate\Database\Eloquent\SoftDeletes;

class Role extends Model implements RoleInterface, PermissibleInterface
{
    use PermissibleTrait;
    // use SoftDeletes;
    // protected $dates = ['deleted_at'];
    /**
     * {@inheritDoc}
     */
    protected $table = 'roles';
    //public $child_roles;
    /**
     * {@inheritDoc}
     */
    protected $fillable = [
        'name',
        'slug',
        'parent_id',
        'is_group',
        'child_roles',
        'permissions',
    ];

    /**
     * The Eloquent users model name.
     *
     * @var string
     */
    protected static $usersModel = 'App\User';//'Cartalyst\Sentinel\Users\EloquentUser';

    /**
     * The Users relationship.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function users()
    {
        return $this->belongsToMany(static::$usersModel, 'role_users', 'role_id', 'user_id')->withTimestamps();
    }

    /**
     * Get mutator for the "permissions" attribute.
     *
     * @param  mixed  $permissions
     * @return array
     */
    public function getPermissionsAttribute($permissions)
    {
        return $permissions ? json_decode($permissions, true) : [];
    }

    /**
     * Set mutator for the "permissions" attribute.
     *
     * @param  mixed  $permissions
     * @return void
     */
    public function setPermissionsAttribute(array $permissions)
    {
        $this->attributes['permissions'] = $permissions ? json_encode($permissions) : '';
    }
    public function setGroupAttribute(array $roles)
    {
        $this->attributes['permissions'] = $roles ? json_encode($roles) : '';
    }
    /**
     * {@inheritDoc}
     */
    public function getRoleId()
    {
        return $this->getKey();
    }
    
    public function parent(){
        return $this->belongsTo('App\Role', 'parent_id');
    }

    /**
     * {@inheritDoc}
     */
    public function getRoleSlug()
    {
        return $this->slug;
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * {@inheritDoc}
     */
    public static function getUsersModel()
    {
        return static::$usersModel;
    }

    /**
     * {@inheritDoc}
     */
    public static function setUsersModel($usersModel)
    {
        static::$usersModel = $usersModel;
    }

    /**
     * Dynamically pass missing methods to the permissions.
     *
     * @param  string  $method
     * @param  array  $parameters
     * @return mixed
     */
    public function __call($method, $parameters)
    {
        $methods = ['hasAccess', 'hasAnyAccess'];

        if (in_array($method, $methods)) {
            $permissions = $this->getPermissionsInstance();

            return call_user_func_array([$permissions, $method], $parameters);
        }

        return parent::__call($method, $parameters);
    }

    /**
     * {@inheritDoc}
     */
    protected function createPermissions()
    {
        return new static::$permissionsClass($this->permissions);
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\role;
use Sentinel;
use Route;

class roleController extends Controller
{
    public function index()
    {
        $roles = role::all();
        //dd($roles);
        return view('role.index',compact('roles'));
    }

    
    public function create()
    {
        return view('role.create');
    }

    
    public function store(Request $request)
    {
        $request->validate([
            'slug' => 'required|unique:roles',
            'name' => 'required',
        ]);
        $permission = ['{"home.dashboard":true}'];
        //dd($permission);
        $role = new role;
        $role->slug = $request->slug;
        $role->name = $request->name;
        $role->permissions = $permission;
        
        if($role->save()){
            return redirect()->route('role-akun.index');
        }else{
            return redirect()->back();
        }   
    }

    
    public function show($id)
    {
        $users = null;
        if($id){
            $role = Sentinel::findRoleBySlug($id);
            $users = $role->users()->get();
        }
        return view('user.index',compact('users'));
    }

    public function edit($id)
    {
        $role = Sentinel::findRoleBySlug($id);
        return view('role.edit',compact('role'));
    }

    
    public function update(Request $request, $id)
    {
        $request->validate([
            'slug' => 'required',
            'name' => 'required',
        ]);
        $role = role::find($id);
        $role->slug = $request->slug;
        $role->name = $request->name;
        $role->save();

        return redirect()->route('role-akun.index');
    }

    
    public function destroy($id)
    {
        $role = role::find($id);
        if($role->delete()){
            return redirect()->route('role-akun.index');
        }else{
            return redirect()->route('role-akun.index');
        }
    }

    public function permissions($id)
    {
        //dd([$id]);
        $role = Sentinel::findRoleBySlug($id);
        
        $routes = Route::getRoutes();
        $actions = [];
        foreach ($routes as $route) {
            if ($route->getName() != "" && !substr_count($route->getName(), 'payment')) {
                $actions[] = $route->getName();
            }            
        }
    
        $var = [];
        $i = 0;
        foreach ($actions as $action) {

            $input = preg_quote(explode('.', $action )[0].".", '~');
            $var[$i] = preg_grep('~' . $input . '~', $actions);
            $actions = array_values(array_diff($actions, $var[$i]));
            $i += 1;
        }
        $actions = array_filter($var);
        //dd([$role,$actions]);
        return View('role.permission', compact('role', 'actions'));
    }

    public function simpan($id, Request $request)
    {
        $role = Sentinel::findRoleById($id);
        $role->permissions = [];
        if($request->permissions){
            foreach ($request->permissions as $permission) {
                if(explode('.', $permission)[1] == 'create'){
                    $role->addPermission($permission);
                    $role->addPermission(explode('.', $permission)[0].".store");                
                }
                else if(explode('.', $permission)[1] == 'edit'){
                    $role->addPermission($permission);
                    $role->addPermission(explode('.', $permission)[0].".update");                
                }
                else{
                    $role->addPermission($permission);
                }            
            }  
        }
        $role->save();
        return redirect()->route('role-akun.index');
    }
}

resources/views/role/_form.blade.php
<div class="form-group form-float">
    <div class="form-line">
        {!! Form::text('slug', null, ['class'=>'form-control','maxlength'=>'30', 'minlength'=>'3', 'required']) !!}
        <label class="form-label">Slug</label>
    </div>
    <div class="help-info">Min. 3, Max. 30 characters</div>
</div>
<div class="form-group form-float">
    <div class="form-line">
        {!! Form::text('name', null, ['class'=>'form-control','maxlength'=>'30', 'minlength'=>'3', 'required']) !!}
        <label class="form-label">Name</label>
    </div>
    <div class="help-info">Min. 3, Max. 30 characters</div>
</div>

resources/views/role/create.blade.php
@extends('potongan.main')

@section('title')
	Create Role User
@stop

@section('content')
	<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Create Role User
                        <small></small>
                    </h2>
                </div>
                <div class="body">
                    {{ Form::open(array('url' => route('role-akun.store'), 'files' => true)) }}
                        
                    	@include('role._form')

                        <br>
                        <button type="reset" class="btn btn-primary m-t-15 waves-effect">Reset</button>
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Simpan</button>
                        <button type="button" class="btn btn-primary m-t-15 waves-effect">back</button>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')
    <!-- Jquery Validation Plugin Css -->
    <script src="{{ asset('template/plugins/jquery-validation/jquery.validate.js') }}"></script>

    <!-- JQuery Steps Plugin Js -->
    <script src="{{ asset('template/plugins/jquery-steps/jquery.steps.js') }}"></script>

    <!-- Sweet Alert Plugin Js -->
    <script src="{{ asset('template/plugins/sweetalert/sweetalert.min.js') }}"></script>

	<script src="{{ asset('template/js/pages/forms/form-validation.js') }}"></script>
	
@stop

@section('style')
	<link href="{{ asset('template/plugins/sweetalert/sweetalert.css') }}" rel="stylesheet" />
@stop

resources/views/role/edit.blade.php
@extends('potongan.main')

@section('title')
	Edit Role User
@stop

@section('content')
	<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Edit Role User
                        <small></small>
                    </h2>
                </div>
                <div class="body">
                    {{ Form::model($role, array('method' => 'PATCH', 'url' => route('role-akun.update', $role->id), 'files' => true)) }}
                    	@include('role._form')

                        <br>
                        <button type="reset" class="btn btn-primary m-t-15 waves-effect">Reset</button>
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Simpan</button>
                        <button type="button" class="btn btn-primary m-t-15 waves-effect">back</button>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')
    <!-- Jquery Validation Plugin Css -->
    <script src="{{ asset('template/plugins/jquery-validation/jquery.validate.js') }}"></script>

    <!-- JQuery Steps Plugin Js -->
    <script src="{{ asset('template/plugins/jquery-steps/jquery.steps.js') }}"></script>

    <!-- Sweet Alert Plugin Js -->
    <script src="{{ asset('template/plugins/sweetalert/sweetalert.min.js') }}"></script>

	<script src="{{ asset('template/js/pages/forms/form-validation.js') }}"></script>
	
@stop

@section('style')
	<link href="{{ asset('template/plugins/sweetalert/sweetalert.css') }}" rel="stylesheet" />
@stop

resources/views/role/index.blade.php
@extends('potongan.main')
	
@section('title')
	Role User
@stop

@section('content')
 <!-- Exportable Table -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Role Table
                </h2>
                <ul class="header-dropdown m-r--5">
                    <a href="{{ route('role-akun.create') }}" class="btn bg-blue-grey waves-effect" class=" text-center">Add New Role
                	</a>
                </ul>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover dataTable js-exportable no-footer" id="tbluser">
                        <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th class="text-center">Name</th>
                                <th class="text-center">Slug</th>
                                <th class="text-center">Peserta</th>
                                <th class="text-center">Edit</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th class="text-center">#</th>
                                <th class="text-center">Name</th>
                                <th class="text-center">Slug</th>
                                <th class="text-center">Peserta</th>
                                <th class="text-center">Edit</th>
                            </tr>
                        </tfoot>
                        <tbody>
                        	<?php $no=0?>
                        	@foreach($roles as $role)
                                <tr>
                                    <td class="text-center">{{++$no}}</td>
                                    <td><a href="{{ route('role-akun.show',$role->slug) }}"> {{$role->slug}}</a></td>
                                    <td><a href="{{ route('role-akun.show',$role->slug) }}"> {{$role->name}}</a></td>
                                    <td>99999++</td>
                                    <td>
                                        <a href="{{ route('role-akun.edit',$role->slug) }}" class="btn btn-info btn-xs waves-effect">Edit</a>
                                        <a href="{{ route('role-akun.permissions',$role->slug) }}" class="btn btn-info btn-xs waves-effect">Permissions</a>
                                        {!! Form::open(['method'=>'DELETE', 'route' => ['role-akun.destroy', $role->id], 'style' => 'display:inline']) !!}
                                        {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs waves-effect','id'=>'delete-confirm']) !!}
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- #END# Exportable Table -->
@stop

@section('script')
	<script src="{{ asset('template/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script type="text/javascript">
        $('.js-exportable').DataTable({
            'info' : false,
            dom: 'Bfrtip',
            responsive: true,
            buttons: [
                'copy', 'csv', 'excel', 'pdf',
            ]
        });
    </script>
@stop

@section('style')
	<link href="{{ asset('template/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet" />
@stop

resources/views/role/permission.blade.php
@extends('potongan.main')

@section('title')
	Give Permissions Role User
@stop

@section('content')
	<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Give Permissions Role User
                        <small></small>
                    </h2>
                </div>
                <div class="body">
                    {{ Form::open(array('url' => route('role-akun.simpan',$role->id),'files' => true)) }}
                    	<div class="row">
                    		@foreach($actions as $action)
	                    		<div class="col-md-4">
	                    			<?php 
					                	$first= array_values($action)[0];
					                    $firstname =explode(".", $first)[0];
					                ?> 
		                            <p>
		                                <b>{{Form::label($firstname, $firstname)}}</b>
		                            </p>
		                            <select name="permissions[]" class="form-control show-tick" multiple data-selected-text-format="count">
		                                @foreach($action as $act)
				                            @if(explode(".", $act)[0]=="api")
				                                <option value="{{$act}}" {{array_key_exists($act, $role->permissions)?"selected":""}}>
				                                {{isset(explode(".", $act)[2])?explode(".", $act)[1].".".explode(".", $act)[2]:explode(".", $act)[1]}}</option>
				                            @else
				                                <option value="{{$act}}" {{array_key_exists($act, $role->permissions)?"selected":""}}>

				                                {{explode(".", $act)[1]}}
				      
				                                </option>
				                            @endif
				                        @endforeach
		                            </select>
		                        </div>
		                    @endforeach
                    	</div>
                    	<div class="text-center">
	                        <button type="reset" class="btn btn-primary m-t-15 waves-effect">Reset</button>
	                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Simpan</button>
	                        <a href="{{ route('role-akun.index') }}" class="btn btn-primary m-t-15 waves-effect" >Back</a>
                    	</div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')
    <!-- Jquery Validation Plugin Css -->
    <script src="{{ asset('template/plugins/jquery-validation/jquery.validate.js') }}"></script>

    <!-- JQuery Steps Plugin Js -->
    <script src="{{ asset('template/plugins/jquery-steps/jquery.steps.js') }}"></script>

    <!-- Sweet Alert Plugin Js -->
    <script src="{{ asset('template/plugins/sweetalert/sweetalert.min.js') }}"></script>

	<script src="{{ asset('template/js/pages/forms/form-validation.js') }}"></script>

    <!-- Multi Select Plugin Js -->
    <script src="{{ asset('template/plugins/multi-select/js/jquery.multi-select.js') }}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset('template/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>
{{-- 
    <script src="{{ asset('template/js/pages/forms/advanced-form-elements.js') }}"></script>
	 --}}
@stop

@section('style')

	<!-- Multi Select Css -->
    <link href="{{ asset('template/plugins/multi-select/css/multi-select.css') }}" rel="stylesheet">

    <!-- Bootstrap Select Css -->
    <link href="{{ asset('template/plugins/bootstrap-select/css/bootstrap-select.css') }}" rel="stylesheet" />

	<link href="{{ asset('template/plugins/sweetalert/sweetalert.css') }}" rel="stylesheet" />
@stop