routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome'); 
});
Auth::routes();
Route::get('login','loginController@login');
Route::post('login','loginController@masuk');
Route::post('logout','loginController@keluar');
Route::post('daftar','loginController@mendaftar');
Route::get('daftar','loginController@daftar');

Route::group(['middleware' => ['web', 'auth', 'permission'] ], function () {

	Route::get('dashboard', 'berkasController@break')->name('home.dashboard');

	//user
	Route::resource('pemilik-akun','userController');
	//role dan pembagian lomba
	Route::resource('role-akun','RoleController');
	Route::get('permission-akun/{id}','RoleController@permissions')->name('role-akun.permissions');
	Route::post('permission-akun/{id}','RoleController@simpan')->name('role-akun.simpan');

	//provinsi
	Route::resource('provinsi','ProvinsiController');
	//kabupaten - kota
	Route::resource('kabupaten-kota','KabKotaController');
	//kecamatan
	Route::resource('kecamatan','kecamatanController');
	//sekolah
	Route::resource('sekolah','SekolahController');
	//universitas
	Route::resource('universitas','UniversitasController');
	//pelajar-profil
	Route::resource('pelajar-profil','PelajarProfilController');
	//mahasiswa-profil
	Route::resource('mahasiswa','MahasiswaProfilController');
	//kelompok
	Route::resource('kelompok', 'KelompokController');
	//kegiatan
	route::resource('kegiatan', 'KegiatanController');
	//user lomba
	route::resource('user-lomba', 'UserLombaController');

	//berkas-user
	route::get('berkas/{user}/{id}', 'berkasController@index')->name('berkas.index');
	//hackathon-user
	route::get('hackathon/{user}/{id}', 'berkasController@indexhack')->name('hackathon.index');
	//ktm
	route::patch('upload-ktm/{id}', 'berkasController@ktm')->name('hackathon.ktm');
	//foto
	route::patch('upload-foto/{id}', 'berkasController@foto');
	//bayar hackathon
	route::patch('upload-bayar/{id}', 'berkasController@bayar');
	//membuat group
	route::post('hackathon-gruop', 'berkasController@makegrup')->name('hackathon.grup');
	//menambahkan anggota
	route::post('hackathon-anggota', 'berkasController@addanggota')->name('hackathon.addanggota');
	//proposal
	route::post('upload-proposal/{id}', 'berkasController@addproposal')->name('hackathon.proposal');
	route::DELETE('del-proposal/{id}/delete', 'berkasController@dellproposal')->name('hackathon.dellproposal');

	route::get('password', 'userController@password');
	route::patch('gantipassword', 'userController@ganti');

	route::get('profil/{nama}/{id}','userController@profil');
	route::get('editprofil/{nama}/{id}','userController@editprofil');

	route::get('bukti-pembayaran','userController@bukti');
	route::post('perbaruiprofil', 'userController@simpanprofil');
});

	//membuka img
	route::get('foto/{type}/{file_id}', 'berkasController@file');
	route::get('tambah-sekolah', 'SekolahController@sekolah');
	route::get('tambah-universitas', 'UniversitasController@universitas');
	route::post('tambah-universitas', 'UniversitasController@simpanuni');
	route::post('tambah-sekolah', 'SekolahController@simpanseko');
	
	route::get('olimpiade-Komputer','KegiatanController@olkom');
	route::get('hackathon','KegiatanController@hack');
	route::get('faq','KegiatanController@faq');
	route::post('faqt','KegiatanController@faqt');

app/Http/Controllers/userController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\user;
use App\mahasiswa_profil as mahasiswa;
use App\pelajar_profil as pelajar;
use App\universitas;
use App\sekolah;
use Sentinel;
use Activation;

class userController extends Controller
{
 	public function index()
 	{
 		$users = user::all();
 		return view('user.index',compact('users'));
 	}

 	public function create()
 	{
 		return view('user.create');
 	}

 	public function store(Request $request)
    {
        $request->validate([
        	'username' => 'required|unique:users',
            'nama' => 'required',
            'email' => 'required',
            'no_hp' => 'required',
            'password' => 'required|same:password_confirm',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            //'jenis_kelamin' => 'required',
            'kecamatan_id' => 'required',
        ]);
        //dd($request->request);
        $user = new user;
        $user->username = $request->username;
        $user->nama = $request->nama;
        $user->email = $request->email;
        $user->no_hp = $request->no_hp;
        $user->password = bcrypt($request->password);
        $user->tempat_lahir = $request->tempat_lahir;
        $user->tanggal_lahir = $request->tanggal_lahir;
        $user->jenis_kelamin = $request->jenis_kelamin;
        $user->kecamatan_id = $request->kecamatan_id;
        $user->alamat = $request->alamat;
        if($user->save()){
            $activation = Activation::create($user);
            $activation = Activation::complete($user, $activation->code);
        	return redirect()->route('pemilik-akun.index');
        }else{
        	return redirect()->back();
        }
    }

    
    public function show($id)
    {
        $user = user::find($id);
        return view('user.show');
    }

    
    public function edit($id)
    {
        $user = user::find($id);
        return view('user.edit',compact('user'));
    }

    
    public function update(Request $request, $id)
    {
        $request->validate([
            'username' => 'required',
            'nama' => 'required',
            'email' => 'required',
            'no_hp' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'jenis_kelamin' => 'required',
            'kecamatan_id' => 'required',
        ]);

        $user = user::find($id);
        $user->username = $request->username;
        $user->nama = $request->nama;
        $user->email = $request->email;
        $user->no_hp = $request->no_hp;
        $user->password = bcrypt($request->password);
        $user->tempat_lahir = $request->tempat_lahir;
        $user->tanggal_lahir = $request->tanggal_lahir;
        $user->jenis_kelamin = $request->jenis_kelamin;
        $user->kecamatan_id = $request->kecamatan_id;
        $user->alamat = $request->alamat;
        if($user->save()){
            
            return redirect()->route('pemilik-akun.index');
        }else{
            return redirect()->back();
        }
    }

    
    public function destroy($id)
    {
        $user = user::find($id);
        //dd([$user,$id]);
        if($user->delete()){
        	return redirect()->route('pemilik-akun.index');
        }else{
        	return redirect()->back();
        }
    }

    public function password()
    {
        return view('uiuser.gantipassword');
    }

    public function ganti(Request $request)
    {
        $request->validate([
            'password' => 'required|same:password_confirm|min:6',
        ]);
        $user = user::find(Sentinel::getuser()->id);
        $user->password = bcrypt($request->password);
        if($user->update()){
            toast()->success('Berhasil Mengganti Password');
        }else{
            toast()->error('Gagal Mengganti Password');
        }

        return redirect()->back();
    }

    public function profil($nama, $id)
    {
        $user = user::find($id);
        return view('uiuser.profil',compact('user'));
    }

    public function editprofil()
    {
        $universitas = universitas::select('id','nama')->get();
        $sekolah = sekolah::select('id','nama')->get();
        return view('uiuser.editprofil',compact('universitas','sekolah'));
    }

    public function simpanprofil(Request $request)
    {
        //dd($request->request);
        $id = Sentinel::getuser()->id;
        $user = user::find($id);
        $mahasiswa = mahasiswa::find($id);
        $pelajar = pelajar::find($id);

        if($request->nama){
            $user->nama = $request->nama;
        }

        if($request->nim){
            $mahasiswa->nim = $request->nim;
        }elseif($request->nisn){
            $pelajar->nisn = $request->nisn;
        }

        if($request->email){
            $user->email = $request->email;
        }

        if($request->no_hp){
            $user->no_hp = $request->no_hp;
        }

        if($request->email){
            $user->email = $request->email;
        }

        if($request->universitas){
            $mahasiswa->universitas_id = $request->universitas;
        }elseif($request->sekolah){
            $pelajar->sekolah_id = $request->sekolah;
        }

        if($request->jurusan){
            $mahasiswa->jurusan = $request->jurusan;
        }

        if($request->jenis_kelamin){
            $user->jenis_kelamin = $request->jenis_kelamin;
        }

        if($request->tempat_lahir){
            $user->tempat_lahir = $request->tempat_lahir;
        }

        if($request->tanggal_lahir){
            $user->tanggal_lahir = $request->tanggal_lahir;
        }

        if($request->alamat){
            $user->alamat = $request->alamat;
        }
        //dd([$request->request, $user, $mahasiswa, $pelajar]);
        if($user->update()){
            if($mahasiswa){
                //dd($mahasiswa);
                $mahasiswa->update();
            }elseif($pelajar){
                //dd($request->mahasiswa);
                $pelajar->update();
            }else{
                //dd([$request->mahasiswa, $request->pelajar]);
                return redirect()->back();
            }
            return redirect('profil/'.Sentinel::getuser()->nama.'/'.Sentinel::getuser()->id);
        }

        return redirect()->back();
    }

    public function bukti()
    {
        return view('uiuser.bukti');
    }
}

resources/views/user/_form.blade.php
<div class="form-group form-float">
    <div class="form-line">
        {!! Form::text('username', null, ['class'=>'form-control','maxlength'=>'10', 'minlength'=>'3', 'required']) !!}
        <label class="form-label">Username</label>
    </div>
    <div class="help-info">Min. 3, Max. 10 characters</div>
</div>

<div class="form-group form-float">
    <div class="form-line">
        {!! Form::text('nama', null, ['class'=>'form-control','maxlength'=>'30', 'minlength'=>'3', 'required']) !!}
        <label class="form-label">Nama</label>
    </div>
    <div class="help-info">Min. 3, Max. 30 characters</div>
</div>

<div class="form-group form-float">
    <div class="form-line">
        {!! Form::email('email', null, ['class'=>'form-control email', 'required']) !!}
        <label class="form-label">Email</label>
    </div>
    <div class="help-info">Email use @</div>
</div>

<div class="form-group form-float">
    <div class="form-line">
        {!! Form::text('no_hp', null, ['class'=>'form-control mobile-phone-number', 'required']) !!}
        <label class="form-label">NO HP</label>
    </div>
    <div class="help-info">use 0-10</div>
</div>

<div class="form-group form-float">
    <div class="form-line">
        {!! Form::password('password', ['class'=>'form-control','required']) !!}
        <label class="form-label">Password</label>
    </div>
    <div class="help-info"></div>
</div>

<div class="form-group form-float">
    <div class="form-line">
        {!! Form::password('password_confirm', ['class'=>'form-control','required']) !!}
        <label class="form-label">Password Confirm</label>
    </div>
    <div class="help-info"></div>
</div>

<div class="form-group form-float">
    <div class="form-line">
        {!! Form::text('tempat_lahir', null, ['class'=>'form-control','maxlength'=>'10', 'minlength'=>'3', 'required']) !!}
        <label class="form-label">Tempat Lahir</label>
    </div>
    <div class="help-info"></div>
</div>

<div class="form-group form-float">
    <div class="form-line">
        {!! Form::text('tanggal_lahir', null, ['class'=>'datepicker form-control', 'required', 'placeholder' => "Tanggal Lahir"]) !!}
    </div>
    <div class="help-info"></div>
</div>

<div class="form-group form-float">
        <input name="jenis_kelamin" type="radio" id="LL" value="LL" class="with-gap radio-col-red"/>
        <label for="LL">LL</label> 
        <input name="jenis_kelamin" type="radio" id="PP" value="PP" class="with-gap radio-col-red"/>
        <label for="PP">PP</label> 

        {!! Form::radio('jenis_kelamin', 'L', ['class'=>'with-gap radio-col-red', 'id' => 'L']) !!}
        <label for="L">Laki - Laki</label> 
        {!! Form::radio('jenis_kelamin', 'P', ['class'=>'with-gap radio-col-red', 'id' => 'P']) !!}
        <label for="P">Perempuan</label> 
</div>

<div class="form-group form-float">
    <div class="form-line">
        {!! Form::text('provinsi', null, ['class'=>'form-control', 'required']) !!}
        <label class="form-label">Provinsi</label>
    </div>
    <div class="help-info"></div>
</div>

<div class="form-group form-float">
    <div class="form-line">
        {!! Form::text('kab_kota', null, ['class'=>'form-control', 'required']) !!}
        <label class="form-label">Kabupaten & Kota</label>
    </div>
    <div class="help-info"></div>
</div>

<div class="form-group form-float">
    <div class="form-line">
        {!! Form::text('kecamatan_id', null, ['class'=>'form-control', 'required']) !!}
        <label class="form-label">Kecamatan</label>
    </div>
    <div class="help-info"></div>
</div>

<div class="form-group form-float">
    <div class="form-line">
        {!! Form::textarea('alamat', null, ['class'=>'form-control', 'required']) !!}
        <label class="form-label">Alamat</label>
    </div>
    <div class="help-info"></div>
</div>

resources/views/user/create.blade.php
@extends('potongan.main')

@section('title')
	Create User
@stop

@section('content')
	<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>Create User - Admin</h2>
                </div>
                <div class="body">
                    {{ Form::open(array('url' => route('pemilik-akun.store'), 'files' => true)) }}
                        
                        @include('user._form')

                        <br>
                        <div class="text-center">
                            <button type="reset" class="btn btn-primary m-t-15 waves-effect">Reset</button>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Simpan</button>
                            <a href="{{ route('pemilik-akun.index') }}" class="btn btn-primary m-t-15 waves-effect">Back</a>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')

     <script src="{{ asset('template/plugins/jquery/jquery.min.js') }}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{{ asset('template/plugins/bootstrap/js/bootstrap.js') }}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset('template/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{{ asset('template/plugins/jquery-slimscroll/jquery.slimscroll.js') }}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset('template/plugins/node-waves/waves.js') }}"></script>

    <!-- Autosize Plugin Js -->
    <script src="{{ asset('template/plugins/autosize/autosize.js') }}"></script>

    <!-- Moment Plugin Js -->
    <script src="{{ asset('template/plugins/momentjs/moment.js') }}"></script>

    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="{{ asset('template/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js') }}"></script>

    <script src="{{ asset('template/js/pages/forms/basic-form-elements.js') }}"></script>
	
@stop

@section('style')

    <!-- Bootstrap Core Css -->
    <link href="{{ asset('template/plugins/bootstrap/css/bootstrap.css') }}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset('template/plugins/node-waves/waves.css') }}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset('template/plugins/animate-css/animate.css') }}" rel="stylesheet" />

    <!-- Bootstrap Material Datetime Picker Css -->
    <link href="{{ asset('template/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css') }}" rel="stylesheet" />

    <!-- Wait Me Css -->
    <link href="{{ asset('template/plugins/waitme/waitMe.css') }}" rel="stylesheet" />

    <!-- Bootstrap Select Css -->
    <link href="{{ asset('template/plugins/bootstrap-select/css/bootstrap-select.css') }}" rel="stylesheet" />
@stop

resources/views/user/edit.blade.php
@extends('potongan.main')

@section('title')
	Create User
@stop

@section('content')
	<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>Create User - Admin</h2>
                </div>
                <div class="body">
                    {{ Form::model($user, array('method' => 'PATCH', 'url' => route('pemilik-akun.update', $user->id), 'files' => true)) }}
                    
                        @include('user._form')

                        <br>
                        <div class="text-center">
                            <button type="reset" class="btn btn-primary m-t-15 waves-effect">Reset</button>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">Simpan</button>
                            <a href="{{ route('pemilik-akun.index') }}" class="btn btn-primary m-t-15 waves-effect">Back</a>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@stop

@section('script')

     <script src="{{ asset('template/plugins/jquery/jquery.min.js') }}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{{ asset('template/plugins/bootstrap/js/bootstrap.js') }}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset('template/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{{ asset('template/plugins/jquery-slimscroll/jquery.slimscroll.js') }}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset('template/plugins/node-waves/waves.js') }}"></script>

    <!-- Autosize Plugin Js -->
    <script src="{{ asset('template/plugins/autosize/autosize.js') }}"></script>

    <!-- Moment Plugin Js -->
    <script src="{{ asset('template/plugins/momentjs/moment.js') }}"></script>

    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="{{ asset('template/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js') }}"></script>

    <script src="{{ asset('template/js/pages/forms/basic-form-elements.js') }}"></script>
	
@stop

@section('style')

    <!-- Bootstrap Core Css -->
    <link href="{{ asset('template/plugins/bootstrap/css/bootstrap.css') }}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset('template/plugins/node-waves/waves.css') }}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset('template/plugins/animate-css/animate.css') }}" rel="stylesheet" />

    <!-- Bootstrap Material Datetime Picker Css -->
    <link href="{{ asset('template/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css') }}" rel="stylesheet" />

    <!-- Wait Me Css -->
    <link href="{{ asset('template/plugins/waitme/waitMe.css') }}" rel="stylesheet" />

    <!-- Bootstrap Select Css -->
    <link href="{{ asset('template/plugins/bootstrap-select/css/bootstrap-select.css') }}" rel="stylesheet" />
@stop

resources/views/user/index.blade.php
@extends('potongan.main')

@section('title')
	User Management
@stop

@section('style')

	<link href="{{ asset('template/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet" />

@stop
@section('content')
    <!-- Exportable Table -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        User Table
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <a href="{{ route('pemilik-akun.create') }}" class="btn bg-blue-grey waves-effect" class=" text-center">Add User
                    	</a>
                    </ul>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover dataTable js-exportable no-footer" id="tbluser">
                            <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th class="text-center">Username</th>
                                    <th class="text-center">Nama Lengkap</th>
                                    <th class="text-center">Email</th>
                                    <th class="text-center">Terakhir Login</th>
                                    <th class="text-center">Aksi</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th class="text-center">Username</th>
                                    <th class="text-center">Nama Lengkap</th>
                                    <th class="text-center">Email</th>
                                    <th class="text-center">Terakhir Login</th>
                                    <th class="text-center">Aksi</th>
                                </tr>
                            </tfoot>
                            <tbody>
                            	<?php $no=0?>
                            	@foreach($users as $user)
	                                <tr>
	                                    <td class="text-center">{{++$no}}</td>
	                                    <td><a href="{{ route('pemilik-akun.show',$user->id) }}">{{$user->username}} </a></td>
	                                    <td>{{$user->nama}}</td>
	                                    <td>{{$user->email}}</td>
	                                    <td>{{$user->last_login}}</td>
                                        <td>
                                            <a href="{{ route('pemilik-akun.edit',$user->id) }}" class="btn btn-info btn-xs waves-effect"> Edit </a>
                                             {!! Form::open(['method'=>'DELETE', 'route' => ['pemilik-akun.destroy', $user->id], 'style' => 'display:inline']) !!}
                                              {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs waves-effect','id'=>'delete-confirm']) !!}
                                              {!! Form::close() !!}
                                        </td>
	                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <button type="button" class="btn btn-info waves-effect" disabled="disabled">
                            <i class="material-icons">mode_edit</i>
                            <span>EDIT</span>
                        </button>
                        <button type="button" class="btn btn-danger waves-effect" disabled="disabled">
                            <i class="material-icons">delete_forever</i>
                            <span>DELETE</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Exportable Table -->
@stop

@section('script')
	
    <script src="{{ asset('template/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('template/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>
    <script type="text/javascript">
        $('.js-exportable').DataTable({
            'info' : false,
            dom: 'Bfrtip',
            responsive: true,
            buttons: [
                'copy', 'csv', 'excel', 'pdf',
            ]
        });
    </script>
    
@stop